services:
  app:
    build:
      context: ..
      dockerfile: 'dev/Dockerfile'
    environment:
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '3000:3000'
    volumes:
      - ..:/app
    networks:
      - app-network
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: